apiVersion: v1
kind: Service
metadata:
  name: webapp1-service
spec:
  type: NodePort
  selector:
    app: webapp1
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30100